# Use postgres/example user/password credentials

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: alina
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: db_bookstore
      
    ports:
      - 5432:5432
